const data = [
    {
        "slug": "50-years-after-the-moon-landing-how-close-is-space-travel-really",
        "postFormat": "standard",
        "title": "50 Years After The Moon Landing How Close Is Space Travel, Really",
        "excerpt": "Cras sit amet maximus odio, finibus pulvinar nisl. Praesent sed sagittis diam. Integer sed volutpat mi, in ultrices tellus.",
        "featureImg": "/images/posts/post_2.jpg",
        "cate": "News",
        "cate_bg": "bg-color-purple-one",
        "cate_img": "/images/category/travel.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Jun 30 2020",
        "post_views": "2K Views",
        "post_share": "250 Shares"
    },
    {
        "slug": "barbecue-party-tips-for-a-truly-amazing-event",
        "postFormat": "quote",
        "title": "Barbecue Party Tips For A Truly Amazing Event",
        "excerpt": "Ut et feugiat dui. Nam fringilla, sem et mollis tincidunt, eros orci congue magna, eget lacinia erat metus vel tortor. Praesent efficitur ultricies felis.",
        "featureImg": "/images/posts/post_18.jpg",
        "cate": "News",
        "cate_bg": "bg-color-red-two",
        "cate_img": "/images/category/food.png",
        "author_name": "Ahmad Nazeri",
        "author_img": "/images/author/ahmad_nazeri.png",
        "date": "May 21 2021",
        "post_views": "1K Views",
        "post_share": "250 Shares"
    },
    {
        "slug": "boxed-water-partners-with-rag-bone-to-tap-consumer-creativity",
        "postFormat": "standard",
        "trending": true,
        "title": "Boxed Water Partners With Rag & Bone To Tap Consumer Creativity",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_5.jpg",
        "cate": "Study",
        "cate_bg": "bg-color-green-one",
        "cate_img": "/images/category/lifestyle.png",
        "author_name": "Ahmad Nazeri",
        "author_img": "/images/author/ahmad_nazeri.png",
        "date": "Jun 08 2022",
        "post_views": "2K Views",
        "post_share": "200 Shares"
    },
    {
        "slug": "crispy-air-fryer-parmesan-and-thyme-roasted-wedge-fries",
        "postFormat": "standard",
        "trending": true,
        "title": "Crispy Air Fryer Parmesan And Thyme Roasted Wedge Fries",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_7.jpg",
        "cate": "Discussion",
        "cate_bg": "bg-color-red-two",
        "cate_img": "/images/category/food.png",
        "author_name": "Xu Jianhong",
        "author_img": "/images/author/xu_jianhong.png",
        "date": "Jun 21 2022",
        "post_views": "1K Views",
        "post_share": "250 Shares"
    },
    {
        "slug": "deep-fryer-pieces-of-wisdom",
        "postFormat": "text",
        "title": "Deep Fryer Pieces Of Wisdom",
        "excerpt": "Ut et feugiat dui. Nam fringilla, sem et mollis tincidunt, eros orci congue magna, eget lacinia erat metus vel tortor. Praesent efficitur ultricies felis.",
        "featureImg": "/images/posts/post_20.jpg",
        "cate": "News",
        "cate_bg": "bg-color-red-two",
        "cate_img": "/images/category/drink.png",
        "author_name": "Nayah Tantoh",
        "author_img": "/images/author/nayah_tantoh.png",
        "date": "Feb 20 2021",
        "post_views": "1K Views",
        "post_share": "250 Shares"
    },
    {
        "slug": "facts-why-inkjet-printing-is-very-appealing-compared",
        "postFormat": "video",
        "story": true,
        "title": "Facts Why Inkjet Printing Is Very Appealing Compared",
        "excerpt": "Nulla euismod ante mattis purus mollis, vitae malesuada orci efficitur. Nunc vulputate augue sapien, eu maximus metus semper eu. Nam eu magna vel tellus tincidunt convallis eget pellentesque nunc. Vestibulum.",
        "featureImg": "/images/posts/post_21.jpg",
        "cate": "Study",
        "cate_bg": "bg-color-blue-one",
        "cate_img": "/images/category/fashion.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Jun 02 2020",
        "post_views": "1K Views",
        "post_share": "310 Shares"
    },
    {
        "slug": "get-around-easily-with-a-new-york-limousine-service",
        "postFormat": "standard",
        "trending": true,
        "title": "Get Around Easily With A New York Limousine Service",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_9.jpg",
        "cate": "Discussion",
        "cate_bg": "bg-color-blue-two",
        "cate_img": "/images/category/sports.png",
        "author_name": "Xu Jianhong",
        "author_img": "/images/author/xu_jianhong.png",
        "date": "Jun 15 2022",
        "post_views": "1K Views",
        "post_share": "210 Shares"
    },
    {
        "slug": "gigi-gorgeous-and-nats-getty-have-a-well-gorgeous-beachside-wedding",
        "postFormat": "video",
        "title": "Gigi Gorgeous And Nats Getty Have A, Well, Gorgeous Beachside Wedding",
        "excerpt": "Nulla euismod ante mattis purus mollis, vitae malesuada orci efficitur. Nunc vulputate augue sapien, eu maximus metus semper eu. Nam eu magna vel tellus tincidunt convallis eget pellentesque nunc. Vestibulum.",
        "featureImg": "/images/posts/post_15.jpg",
        "cate": "Tools",
        "cate_bg": "bg-color-green-one",
        "cate_img": "/images/category/lifestyle.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Jun 02 2018",
        "post_views": "1K Views",
        "post_share": "310 Shares"
    },
    {
        "slug": "here-i-focus-on-a-range-of-items-and-features",
        "postFormat": "standard",
        "trending": true,
        "title": "Here, I Focus On A Range Of Items And Features",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_6.jpg",
        "cate": "Tools",
        "cate_bg": "bg-color-green-two",
        "cate_img": "/images/category/swimming.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Jun 10 2022",
        "post_views": "2K Views",
        "post_share": "200 Shares"
    },
    {
        "slug": "increasing-prosperity-with-positive-thinking",
        "postFormat": "standard",
        "trending": true,
        "title": "Increasing Prosperity With Positive Thinking",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_3.jpg",
        "cate": "Tools",
        "cate_bg": "bg-color-blue-grey-one",
        "cate_img": "/images/category/world.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Jun 01 2020",
        "post_views": "2K Views",
        "post_share": "230 Shares"
    },
    {
        "slug": "kipchoge-proves-he-has-no-equal-runs-2nd-fastest-marathon-time-in-history",
        "postFormat": "standard",
        "trending": true,
        "title": "Kipchoge Proves He Has No Equal Runs 2nd Fastest Marathon Time In History",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_8.jpg",
        "cate": "Tools",
        "cate_bg": "bg-color-blue-three",
        "cate_img": "/images/category/racing.png",
        "author_name": "Sergio Pliego",
        "author_img": "/images/author/sergio_pliego.png",
        "date": "Jun 15 2022",
        "post_views": "1K Views",
        "post_share": "210 Shares"
    },
    {
        "slug": "looking-to-up-your-insta-game-heres-how-to-nail-an-instagram-video",
        "postFormat": "video",
        "title": "Looking To Up Your Insta Game Here’s How To Nail An Instagram Video",
        "excerpt": "Vivamus volutpat odio non odio feugiat placerat. Suspendisse nec mauris at sem accumsan porttitor non sed diam. Proin felis purus, dapibus eu vulputate.",
        "featureImg": "/images/posts/post_17.jpg",
        "cate": "Tools",
        "cate_bg": "bg-color-green-three",
        "cate_img": "/images/category/culture.png",
        "author_name": "Ahmad Nazeri",
        "author_img": "/images/author/ahmad_nazeri.png",
        "date": "Jun 09 2018",
        "post_views": "1K Views",
        "post_share": "150 Shares"
    },
    {
        "slug": "maui-by-air-the-best-way-around-the-island",
        "postFormat": "video",
        "title": "Maui By Air The Best Way Around The Island",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_11.jpg",
        "cate": "Discussion",
        "cate_bg": "bg-color-purple-one",
        "cate_img": "/images/category/travel.png",
        "author_name": "Ashley Graham",
        "author_img": "/images/author/ashley_graham.png",
        "date": "Jun 20 2018",
        "post_views": "1K Views",
        "post_share": "210 Shares"
    },
    {
        "slug": "not-all-blank-cassettes-are-created-equal",
        "postFormat": "standard",
        "story": true,
        "title": "Not All Blank Cassettes Are Created Equal",
        "excerpt": "Nulla euismod ante mattis purus mollis, vitae malesuada orci efficitur. Nunc vulputate augue sapien, eu maximus metus semper eu. Nam eu magna vel tellus tincidunt convallis eget pellentesque nunc. Vestibulum.",
        "featureImg": "/images/posts/post_22.jpg",
        "cate": "Discussion",
        "cate_bg": "bg-color-blue-four",
        "cate_img": "/images/category/cooking.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Jun 04 2020",
        "post_views": "1K Views",
        "post_share": "310 Shares"
    },
    {
        "slug": "smarter-food-choices-101-tips-for-busy-women",
        "postFormat": "standard",
        "title": "Smarter Food Choices 101 Tips For Busy Women",
        "excerpt": "Ut et feugiat dui. Nam fringilla, sem et mollis tincidunt, eros orci congue magna, eget lacinia erat metus vel tortor. Praesent efficitur ultricies felis.",
        "featureImg": "/images/posts/post_19.jpg",
        "cate": "Discussion",
        "cate_bg": "bg-color-red-two",
        "cate_img": "/images/category/food.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "May 20 2021",
        "post_views": "1K Views",
        "post_share": "250 Shares"
    },
    {
        "slug": "stocking-your-restaurant-kitchen-finding-reliable-sellers",
        "postFormat": "standard",
        "story": true,
        "title": "Stocking Your Restaurant Kitchen Finding Reliable Sellers",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_13.jpg",
        "cate": "Discussion",
        "cate_bg": "bg-color-blue-one",
        "cate_img": "/images/category/technology.png",
        "author_name": "David Brown",
        "author_img": "/images/author/david_brown.png",
        "date": "Aug 01 2021",
        "post_views": "1K Views",
        "post_share": "250 Shares"
    },
    {
        "slug": "teslas-cooking-up-a-new-way-to-wire-its-cars-report-says",
        "postFormat": "audio",
        "title": "Tesla’s Cooking Up A New Way To Wire Its Cars, Report Says",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_23.jpg",
        "cate": "Study",
        "cate_bg": "bg-color-blue-one",
        "cate_img": "/images/category/technology.png",
        "author_name": "Ashley Graham",
        "author_img": "/images/author/ashley_graham.png",
        "date": "Jun 10 2022",
        "post_views": "1K Views",
        "post_share": "210 Shares"
    },
    {
        "slug": "to-keep-makeup-looking-fresh-take-a-powder",
        "postFormat": "video",
        "title": "To Keep Makeup Looking Fresh Take A Powder",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_14.jpg",
        "cate": "Study",
        "cate_bg": "bg-color-blue-one",
        "cate_img": "/images/category/fashion.png",
        "author_name": "Sergio Pliego",
        "author_img": "/images/author/sergio_pliego.png",
        "date": "Jun 20 2018",
        "post_views": "1K Views",
        "post_share": "310 Shares"
    },
    {
        "slug": "trip-to-iqaluit-in-nunavut-a-canadian-arctic-city",
        "postFormat": "gallery",
        "title": "Trip To Iqaluit In Nunavut A Canadian Arctic City",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_4.jpg",
        "cate": "Study",
        "cate_bg": "bg-color-green-one",
        "cate_img": "/images/category/lifestyle.png",
        "author_name": "Xu Jianhong",
        "author_img": "/images/author/xu_jianhong.png",
        "date": "Jun 05 2022",
        "post_views": "2K Views",
        "post_share": "230 Shares"
    },
    {
        "slug": "unmatched-toner-cartridge-quality-20-less-than-oem-price",
        "postFormat": "standard",
        "story": true,
        "title": "Unmatched Toner Cartridge Quality 20 Less Than Oem Price",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_12.jpg",
        "cate": "Study",
        "cate_bg": "bg-color-purple-two",
        "cate_img": "/images/category/beauty.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Aug 02 2021",
        "post_views": "1K Views",
        "post_share": "210 Shares"
    },
    {
        "slug": "vr-is-the-use-of-computer-technology-to-create-a-simulated-environment.",
        "postFormat": "standard",
        "title": "VR Is the Use of Computer Technology to Create a Simulated Environment.",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_1.jpg",
        "cate": "News",
        "cate_bg": "bg-color-blue-one",
        "cate_img": "/images/category/technology.png",
        "author_name": "Ashley Graham",
        "author_img": "/images/author/ashley_graham.png",
        "date": "Jun 25 2022",
        "post_views": "2K Views",
        "post_share": "230 Shares"
    },
    {
        "slug": "want-to-win-a-travelPro-bag",
        "postFormat": "video",
        "title": "Want to win a travel Pro bag",
        "excerpt": "Ut et feugiat dui. Nam fringilla, sem et mollis tincidunt, eros orci congue magna, eget lacinia erat metus vel tortor. Praesent efficitur ultricies felis.",
        "featureImg": "/images/posts/post_16.jpg",
        "cate": "News",
        "cate_bg": "bg-color-blue-grey-one",
        "cate_img": "/images/category/contests.png",
        "author_name": "Amachea Jajah",
        "author_img": "/images/author/amachea_jajah.png",
        "date": "Jun 03 2018",
        "post_views": "1K Views",
        "post_share": "310 Shares"
    },
    {
        "slug": "world-travel-holdings-will-be-honored-alongside-other-recipients",
        "postFormat": "standard",
        "story": true,
        "title": "World Travel Holdings Will Be Honored Alongside Other Recipients",
        "excerpt": "Curabitur egestas est vitae sem blandit tincidunt. Nunc cursus interdum odio sit amet gravida.",
        "featureImg": "/images/posts/post_10.jpg",
        "cate": "News",
        "cate_bg": "bg-color-purple-one",
        "cate_img": "/images/category/travel.png",
        "author_name": "Ashley Graham",
        "author_img": "/images/author/ashley_graham.png",
        "date": "Jun 02 2022",
        "post_views": "1K Views",
        "post_share": "210 Shares"
    }
]

export default data;